# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      security-events: write
      actions: read
      contents: read
      issues: read
      checks: write
      pull-requests: write
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Build Checks
      run: mvn clean verify --file pom.xml --batch-mode --no-transfer-progress
 
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/surefire-reports/*.xml
          
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.3
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
          
    - name: build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with: 
        image: xdlucifer/springboot-images
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Scan Docker image 🐳
      uses: snyk/actions/docker@master
      continue-on-error: true
      with:
        image: docker.io/xdlucifer/springboot-images
        args: --file=Dockerfile --severity-threshold=high --sarif-file-output=snyk.sarif
      env:
        SNYK_TOKEN: b249b6a4-7444-46a2-bdf0-32383f4281a8

    - name: Upload Snyk report as sarif 📦
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
